In [1]:
!pip install nltk
!pip install spacy
!pip install stopwords
import nltk
import spacy
import numpy as np
from nltk.tokenize import TreebankWordTokenizer
from nltk.stem.porter import PorterStemmer
from nltk.stem import WordNetLemmatizer
from nltk.corpus import wordnet
#from TokenizationTest import TokenizationTest
from happyfuntokenizing import Tokenizer as potts
from sklearn.feature_extraction.text import CountVectorizer
from sklearn import preprocessing
from sklearn import linear_model
import pandas as pd
lemmatizer = WordNetLemmatizer()
porter_stemmer = PorterStemmer()

You should consider upgrading via the 'c:\users\14699\appdata\local\programs\python\python38\python.exe -m pip install --upgrade pip' command.


You should consider upgrading via the 'c:\users\14699\appdata\local\programs\python\python38\python.exe -m pip install --upgrade pip' command.
You should consider upgrading via the 'c:\users\14699\appdata\local\programs\python\python38\python.exe -m pip install --upgrade pip' command.


In [2]:
!pip install wordcloud
!pip install gensim
import pandas as pd
import re
import string
import nltk
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize 
from nltk.stem.porter import PorterStemmer
from nltk.stem import WordNetLemmatizer
from collections import Counter
from wordcloud import WordCloud, STOPWORDS
import matplotlib.pyplot as plt
from gensim.models import ldamodel
import gensim.corpora
from sklearn.feature_extraction.text import TfidfVectorizer, CountVectorizer
from nltk import pos_tag,word_tokenize

lemmatizer = WordNetLemmatizer()
porter_stemmer = PorterStemmer()

You should consider upgrading via the 'c:\users\14699\appdata\local\programs\python\python38\python.exe -m pip install --upgrade pip' command.


You should consider upgrading via the 'c:\users\14699\appdata\local\programs\python\python38\python.exe -m pip install --upgrade pip' command.


In [3]:
df_train = pd.read_csv('train.csv', encoding = 'latin-1')
df_train.head()


Id                                               text  Target
0   1  @USAirways  ! THE WORST in customer service. @...      -1
1   2  @united call wait times are over 20 minutes an...      -1
2   3  @JetBlue what's up with the random delay on fl...      -1
3   4  @AmericanAir Good morning!  Wondering why my p...       0
4   5  @united UA 746. Pacific Rim and Date Night cut...      -1

In [4]:
df_train["Target"].value_counts()

-1    4566
 0    1536
 1    1218
Name: Target, dtype: int64

In [5]:
df_train.shape

(7320, 3)

In [6]:
df_test = pd.read_csv('test.csv')
df_test.head()

id                                               text
0  7322  @AmericanAir In car gng to DFW. Pulled over 1h...
1  7323  @AmericanAir after all, the plane didn‰Ûªt lan...
2  7324  @SouthwestAir can't believe how many paying cu...
3  7325  @USAirways I can legitimately say that I would...
4  7326  @AmericanAir still no response from AA. great ...

In [7]:
df_test.shape

(7320, 2)

## data cleaning

In [8]:
combined = df_train.append(df_test,ignore_index= True )

In [9]:
combined.head()

Id                                               text  Target  id
0  1.0  @USAirways  ! THE WORST in customer service. @...    -1.0 NaN
1  2.0  @united call wait times are over 20 minutes an...    -1.0 NaN
2  3.0  @JetBlue what's up with the random delay on fl...    -1.0 NaN
3  4.0  @AmericanAir Good morning!  Wondering why my p...     0.0 NaN
4  5.0  @united UA 746. Pacific Rim and Date Night cut...    -1.0 NaN

In [10]:
combined.shape

(14640, 4)

In [11]:
def remove_pattern(text,pattern):
    text = text.lower()
    r = re.findall(pattern,text)
    for i in r:
        text = re.sub(i,"",text)
    return text

In [12]:
combined["tidy_tweet"] = np.vectorize(remove_pattern)(combined["text"], "@[\w]*")

In [13]:
combined["tidy_tweet"] = combined["tidy_tweet"].str.replace("[^a-zA-Z#]"," ")

In [14]:
combined['tidy_tweet'] = combined['tidy_tweet'].apply(lambda x: ' '.join([w for w in x.split() if len(w)>3]))

In [15]:
combined.head()

Id                                               text  Target  id  \
0  1.0  @USAirways  ! THE WORST in customer service. @...    -1.0 NaN   
1  2.0  @united call wait times are over 20 minutes an...    -1.0 NaN   
2  3.0  @JetBlue what's up with the random delay on fl...    -1.0 NaN   
3  4.0  @AmericanAir Good morning!  Wondering why my p...     0.0 NaN   
4  5.0  @united UA 746. Pacific Rim and Date Night cut...    -1.0 NaN   

                                          tidy_tweet  
0  worst customer service calling over month book...  
1  call wait times over minutes airport wait time...  
2  what with random delay flight chance being fal...  
3  good morning wondering check boarding pass thi...  
4  pacific date night constantly randomly spot re...

### tokenization

In [16]:
tokenised_tweet = combined['tidy_tweet'].apply(lambda x: x.split())
tokenised_tweet.head()

0    [worst, customer, service, calling, over, mont...
1    [call, wait, times, over, minutes, airport, wa...
2    [what, with, random, delay, flight, chance, be...
3    [good, morning, wondering, check, boarding, pa...
4    [pacific, date, night, constantly, randomly, s...
Name: tidy_tweet, dtype: object

## normalization

In [17]:
from nltk.stem.porter import PorterStemmer 
stemmer = PorterStemmer()
tokenised_tweet = tokenised_tweet.apply(lambda x: [stemmer.stem(i) for i in x])
tokenised_tweet.head()

0    [worst, custom, servic, call, over, month, boo...
1    [call, wait, time, over, minut, airport, wait,...
2    [what, with, random, delay, flight, chanc, be,...
3    [good, morn, wonder, check, board, pass, thi, ...
4    [pacif, date, night, constantli, randomli, spo...
Name: tidy_tweet, dtype: object

## Lemmatization

In [18]:
nltk.download('wordnet')
from nltk.stem import WordNetLemmatizer 
lemmatizer = WordNetLemmatizer()
tokenised_tweet = tokenised_tweet.apply(lambda x: [lemmatizer.lemmatize(i) for i in x])
tokenised_tweet.head()

[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\14699\AppData\Roaming\nltk_data...
[nltk_data]   Package wordnet is already up-to-date!


0    [worst, custom, servic, call, over, month, boo...
1    [call, wait, time, over, minut, airport, wait,...
2    [what, with, random, delay, flight, chanc, be,...
3    [good, morn, wonder, check, board, pas, thi, m...
4    [pacif, date, night, constantli, randomli, spo...
Name: tidy_tweet, dtype: object

In [19]:
for i in range(len(tokenised_tweet)):
    tokenised_tweet[i] = ' '.join(tokenised_tweet[i])
    
combined['tidy_tweet'] = tokenised_tweet

In [20]:
combined.head()

Id                                               text  Target  id  \
0  1.0  @USAirways  ! THE WORST in customer service. @...    -1.0 NaN   
1  2.0  @united call wait times are over 20 minutes an...    -1.0 NaN   
2  3.0  @JetBlue what's up with the random delay on fl...    -1.0 NaN   
3  4.0  @AmericanAir Good morning!  Wondering why my p...     0.0 NaN   
4  5.0  @united UA 746. Pacific Rim and Date Night cut...    -1.0 NaN   

                                          tidy_tweet  
0  worst custom servic call over month book fligh...  
1  call wait time over minut airport wait time lo...  
2  what with random delay flight chanc be fals alarm  
3          good morn wonder check board pas thi morn  
4   pacif date night constantli randomli spot repeat

In [21]:
combined.shape

(14640, 5)

### Extracting Features from Cleaned Tweets

In [22]:
!pip install mglearn
%matplotlib inline
from preamble import *

You should consider upgrading via the 'c:\users\14699\appdata\local\programs\python\python38\python.exe -m pip install --upgrade pip' command.
c:\users\14699\appdata\local\programs\python\python38\lib\site-packages\sklearn\externals\six.py:28: FutureWarning: The module is deprecated in version 0.21 and will be removed in version 0.23 since we've dropped support for Python 2.7. Please rely on the official version of six (https://pypi.org/project/six/).
  warnings.warn("The module is deprecated in version 0.21 and will be removed "


c:\users\14699\appdata\local\programs\python\python38\lib\site-packages\sklearn\externals\joblib\__init__.py:15: FutureWarning: sklearn.externals.joblib is deprecated in 0.21 and will be removed in 0.23. Please import this functionality directly from joblib, which can be installed with: pip install joblib. If this warning is raised when loading pickled models, you may need to re-serialize those models with scikit-learn 0.21+.
  warnings.warn(msg, category=FutureWarning)


In [23]:
from sklearn.feature_extraction.text import TfidfVectorizer, CountVectorizer
import gensim

## Bag-of-Words Features

In [24]:
bow_vect = CountVectorizer(max_df=0.90, min_df=5,max_features=1000, stop_words='english')
bow = bow_vect.fit_transform(combined['tidy_tweet'])
bow.shape

(14640, 1000)

In [25]:
print("Dense representation of bow:\n{}".format(
    bow.toarray()))

Dense representation of bow:
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


## TF-IDF Features

In [26]:
from sklearn.feature_extraction.text import TfidfVectorizer
tfidf_vectorizer = TfidfVectorizer(max_df=0.90, min_df=5, max_features=1000, stop_words='english')
# TF-IDF feature matrix
tfidf = tfidf_vectorizer.fit_transform(combined['tidy_tweet'])
tfidf.shape

(14640, 1000)

In [27]:
from sklearn.model_selection import cross_val_score
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import f1_score
from sklearn.preprocessing import MaxAbsScaler

In [28]:
train_bow = bow[:7320,:]
test_bow = bow[7320:,:]

## splitting datasets

In [29]:

xtrain_bow, xvalid_bow, ytrain, yvalid = train_test_split(train_bow,df_train['Target'], random_state=42,test_size=0.2)
lreg = LogisticRegression(C = 10, random_state=100)
lreg.fit(xtrain_bow, ytrain)


c:\users\14699\appdata\local\programs\python\python38\lib\site-packages\sklearn\linear_model\_logistic.py:938: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression(C=10, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=100, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

In [30]:
scores = cross_val_score(LogisticRegression(), xtrain_bow, ytrain, cv=5)
print("Mean cross-validation accuracy: {:.2f}".format(np.mean(scores)))

Mean cross-validation accuracy: 0.75


In [31]:
from sklearn.model_selection import GridSearchCV
param_grid = {'C': [0.001, 0.01, 0.1, 1, 10]}
grid = GridSearchCV(LogisticRegression(max_iter=1000), param_grid, cv=5)
grid.fit(xtrain_bow, ytrain)
print("Best cross-validation score: {:.2f}".format(grid.best_score_))
print("Best parameters: ", grid.best_params_)

Best cross-validation score: 0.75
Best parameters:  {'C': 1}


In [32]:
y = pd.DataFrame(xvalid_bow)

In [33]:
y.head()

0
0    (0, 951)\t1\n  (0, 487)\t1\n  (0, 476)\t1\n ...
1                                        (0, 880)\t1
2    (0, 211)\t1\n  (0, 280)\t1\n  (0, 309)\t1\n ...
3    (0, 346)\t2\n  (0, 892)\t1\n  (0, 8)\t1\n  (...
4    (0, 121)\t2\n  (0, 480)\t1\n  (0, 711)\t1\n ...

## Building model using Bag-of-Words features

### logistic regression

In [34]:
prediction = lreg.predict(xvalid_bow) # predicting on the validation set
f1_score(yvalid, prediction,average='macro') # calculating f1 score

0.6860677457420673

In [35]:
test_pred = lreg.predict(test_bow)
df_test['Target'] = test_pred
submission = df_test[['id','Target']]
submission.to_csv('3hw1_radhika.csv', index=False)

In [36]:
df_test.head()

id                                               text  Target
0  7322  @AmericanAir In car gng to DFW. Pulled over 1h...      -1
1  7323  @AmericanAir after all, the plane didn‰Ûªt lan...      -1
2  7324  @SouthwestAir can't believe how many paying cu...      -1
3  7325  @USAirways I can legitimately say that I would...       0
4  7326  @AmericanAir still no response from AA. great ...       1

## Building model using TF-IDF features


In [37]:
train_tfidf = tfidf[:7320,:]
test_tfidf = tfidf[7320:,:]

In [38]:
xtrain_tfidf = train_tfidf[ytrain.index]
xvalid_tfidf = train_tfidf[yvalid.index]
classifier = lreg.fit(xtrain_tfidf, ytrain)
prediction = classifier.predict(xvalid_tfidf)
f1_score(yvalid, prediction,average='macro')

c:\users\14699\appdata\local\programs\python\python38\lib\site-packages\sklearn\linear_model\_logistic.py:938: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


0.6949240173032875

In [39]:
test_pred = lreg.predict(test_bow)
df_test['Target'] = test_pred
#submission = df_test[['id','Target']]
#submission.to_csv('2hw1_radhika.csv', index=False)

In [40]:
df_test.head()

id                                               text  Target
0  7322  @AmericanAir In car gng to DFW. Pulled over 1h...      -1
1  7323  @AmericanAir after all, the plane didn‰Ûªt lan...      -1
2  7324  @SouthwestAir can't believe how many paying cu...      -1
3  7325  @USAirways I can legitimately say that I would...       0
4  7326  @AmericanAir still no response from AA. great ...       1

## XGBOOST

In [41]:
!pip install xgboost
from xgboost import XGBClassifier

You should consider upgrading via the 'c:\users\14699\appdata\local\programs\python\python38\python.exe -m pip install --upgrade pip' command.


## Building model using Bag-of-Words features

In [42]:
xgb_model = XGBClassifier(max_depth=6, n_estimators=1000).fit(xtrain_bow, ytrain)
prediction = xgb_model.predict(xvalid_bow)
f1_score(yvalid, prediction,average='macro')

0.7037498791701974

In [43]:
test_pred = xgb_model.predict(test_bow)
df_test['Target'] = test_pred
df_test.head

<bound method NDFrame.head of          id                                               text  Target
0      7322  @AmericanAir In car gng to DFW. Pulled over 1h...      -1
1      7323  @AmericanAir after all, the plane didn‰Ûªt lan...      -1
2      7324  @SouthwestAir can't believe how many paying cu...      -1
3      7325  @USAirways I can legitimately say that I would...       0
4      7326  @AmericanAir still no response from AA. great ...      -1
...     ...                                                ...     ...
7315  14637  @JetBlue Traveling with two kids tomorrow (age...       0
7316  14638  @JetBlue Tx for the info. Just don't understan...       0
7317  14639  @AmericanAir I understand. But why is this the...      -1
7318  14640                               @USAirways really!??      -1
7319  14641  @united no I did not make connection.  Your st...      -1

[7320 rows x 3 columns]>

In [44]:
xgb = XGBClassifier(max_depth=6, n_estimators=1000).fit(xtrain_tfidf, ytrain)
prediction = xgb.predict(xvalid_tfidf)
f1_score(yvalid, prediction,average='macro')

0.6625341547342201

In [45]:
test_pred = xgb.predict(test_tfidf)
df_test['Target'] = test_pred
df_test.head

<bound method NDFrame.head of          id                                               text  Target
0      7322  @AmericanAir In car gng to DFW. Pulled over 1h...      -1
1      7323  @AmericanAir after all, the plane didn‰Ûªt lan...      -1
2      7324  @SouthwestAir can't believe how many paying cu...      -1
3      7325  @USAirways I can legitimately say that I would...       0
4      7326  @AmericanAir still no response from AA. great ...       1
...     ...                                                ...     ...
7315  14637  @JetBlue Traveling with two kids tomorrow (age...      -1
7316  14638  @JetBlue Tx for the info. Just don't understan...      -1
7317  14639  @AmericanAir I understand. But why is this the...      -1
7318  14640                               @USAirways really!??      -1
7319  14641  @united no I did not make connection.  Your st...      -1

[7320 rows x 3 columns]>

## Naive bayes

In [46]:
!pip install MultinomialNB
from sklearn.naive_bayes import MultinomialNB
classifier = MultinomialNB(alpha=0.1).fit(xtrain_bow, ytrain)
prediction = classifier.predict(xvalid_bow)
f1_score(yvalid, prediction,average='macro')

ERROR: Could not find a version that satisfies the requirement MultinomialNB (from versions: none)
ERROR: No matching distribution found for MultinomialNB
You should consider upgrading via the 'c:\users\14699\appdata\local\programs\python\python38\python.exe -m pip install --upgrade pip' command.


0.6856321965642644

## Building model using Bag-of-Words features

In [47]:
test_pred = classifier.predict(test_bow)
df_test['Target'] = test_pred
df_test.head

<bound method NDFrame.head of          id                                               text  Target
0      7322  @AmericanAir In car gng to DFW. Pulled over 1h...      -1
1      7323  @AmericanAir after all, the plane didn‰Ûªt lan...      -1
2      7324  @SouthwestAir can't believe how many paying cu...      -1
3      7325  @USAirways I can legitimately say that I would...       0
4      7326  @AmericanAir still no response from AA. great ...       1
...     ...                                                ...     ...
7315  14637  @JetBlue Traveling with two kids tomorrow (age...       0
7316  14638  @JetBlue Tx for the info. Just don't understan...      -1
7317  14639  @AmericanAir I understand. But why is this the...      -1
7318  14640                               @USAirways really!??      -1
7319  14641  @united no I did not make connection.  Your st...      -1

[7320 rows x 3 columns]>

In [48]:
classifier = MultinomialNB(alpha=0.1).fit(xtrain_tfidf, ytrain)
prediction = classifier.predict(xvalid_tfidf)
f1_score(yvalid, prediction,average='macro')

0.6230551397379698

In [49]:
test_pred = classifier.predict(test_tfidf)
df_test['target'] = test_pred
df_test.head

<bound method NDFrame.head of          id                                               text  Target  target
0      7322  @AmericanAir In car gng to DFW. Pulled over 1h...      -1      -1
1      7323  @AmericanAir after all, the plane didn‰Ûªt lan...      -1      -1
2      7324  @SouthwestAir can't believe how many paying cu...      -1      -1
3      7325  @USAirways I can legitimately say that I would...       0       0
4      7326  @AmericanAir still no response from AA. great ...       1       1
...     ...                                                ...     ...     ...
7315  14637  @JetBlue Traveling with two kids tomorrow (age...       0      -1
7316  14638  @JetBlue Tx for the info. Just don't understan...      -1      -1
7317  14639  @AmericanAir I understand. But why is this the...      -1      -1
7318  14640                               @USAirways really!??      -1      -1
7319  14641  @united no I did not make connection.  Your st...      -1      -1

[7320 rows x 4 column